export const cityDetails = [
  {
    id: 1,
    name: "Chicago",
    image: "/image/city.png",
    price: "1150,000",
    sell: "For Sale",
    fashion: "Apartment mosquito fashion House 2002",
    rating: 4.5,
    room: "5 Rooms",
    bathroom: "4 Bathrooms",
    location: "208 Osian Boulevard, Tangail",
  },
  {
    id: 2,
    name: "New York",
    image: "/image/city.png",
    price: "1,200,000",
    sell: "For Sale",
    fashion: "Modern Apartment in Downtown",
    rating: 4.8,
    room: "3 Rooms",
    bathroom: "2 Bathrooms",
    location: "123 Broadway, New York",
  },
  {
    id: 3,
    name: "San Francisco",
    image: "/image/city.png",
    price: "950,000",
    sell: "For Rent",
    fashion: "Luxury Condo with City Views",
    rating: 4.7,
    room: "4 Rooms",
    bathroom: "3 Bathrooms",
    location: "456 Market St, San Francisco",
  },
  {
    id: 4,
    name: "Los Angeles",
    image: "/image/city.png",
    price: "1,300,000",
    sell: "For Sale",
    fashion: "Spacious Family Home",
    rating: 4.6,
    room: "6 Rooms",
    bathroom: "4 Bathrooms",
    location: "789 Sunset Blvd, Los Angeles",
  },
  {
    id: 5,
    name: "Las Vegas",
    image: "/image/city.png",
    price: "800,000",
    sell: "For Sale",
    fashion: "Modern Apartment with Pool",
    rating: 4.4,
    room: "2 Rooms",
    bathroom: "2 Bathrooms",
    location: "101 Strip Blvd, Las Vegas",
  },
  {
    id: 6,
    name: "Seattle",
    image: "/image/city.png",
    price: "1,100,000",
    sell: "For Sale",
    fashion: "Cozy Apartment in the Heart of Seattle",
    rating: 4.5,
    room: "3 Rooms",
    bathroom: "2 Bathrooms",
    location: "202 Pike Place, Seattle",
  },
  {
    id: 7,
    name: "Austin",
    image: "/image/city.png",
    price: "950,000",
    sell: "For Rent",
    fashion: "Charming House with a Garden",
    rating: 4.3,
    room: "4 Rooms",
    bathroom: "3 Bathrooms",
    location: "303 6th St, Austin",
  },
];