export const cityCardData = [
      {     id:1,
            image:"/image/city.png",
            price:"1150,000",
            sell:"For Sale",
            fashion:"Apartment mosquito fashion House 2002",
            rating:4.5,
            room:"5 Rooms",
            batroom:"4 Bathroom",
            location:"208 Osian Bluderved , Tangail"
      },
      {     id:2,
            image:"/image/city.png",
            price:"1150,000",
            sell:"For Sale",
            fashion:"Apartment mosquito fashion House 2002",
            rating:4.5,
            room:"5 Rooms",
            batroom:"4 Bathroom",
            location:"208 Osian Bluderved , Tangail"
      },
      {     id:3,
            image:"/image/city.png",
            price:"1150,000",
            sell:"For Sale",
            fashion:"Apartment mosquito fashion House 2002",
            rating:4.5,
            room:"5 Rooms",
            batroom:"4 Bathroom",
            location:"208 Osian Bluderved , Tangail"
      },
      {     id:4,
            image:"/image/city.png",
            price:"1150,000",
            sell:"For Sale",
            fashion:"Apartment mosquito fashion House 2002",
            rating:4.5,
            room:"5 Rooms",
            batroom:"4 Bathroom",
            location:"208 Osian Bluderved , Tangail"
      },
      {     id:5,
            image:"/image/city.png",
            price:"1150,000",
            sell:"For Sale",
            fashion:"Apartment mosquito fashion House 2002",
            rating:4.5,
            room:"5 Rooms",
            batroom:"4 Bathroom",
            location:"208 Osian Bluderved , Tangail"
      },
      {     id:6,
            image:"/image/city.png",
            price:"1150,000",
            sell:"For Sale",
            fashion:"Apartment mosquito fashion House 2002",
            rating:4.5,
            room:"5 Rooms",
            batroom:"4 Bathroom",
            location:"208 Osian Bluderved , Tangail"
      },
      {     id:7,
            image:"/image/city.png",
            price:"1150,000",
            sell:"For Sale",
            fashion:"Apartment mosquito fashion House 2002",
            rating:4.5,
            room:"5 Rooms",
            batroom:"4 Bathroom",
            location:"208 Osian Bluderved , Tangail"
      },


]